version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15
    container_name: puzzler_postgres_db
    hostname: puzzler-postgres
    ports:
      - "14322:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: puzzler
    volumes:
      - puzzler_postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations/standalone_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - puzzler_internal_network
    labels:
      project: "puzzler"
      service: "database"

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: puzzler_pgadmin
    hostname: puzzler-pgadmin
    ports:
      - "14323:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@puzzler.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - puzzler_pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - puzzler_internal_network
    labels:
      project: "puzzler"
      service: "pgadmin"

networks:
  puzzler_internal_network:
    name: puzzler_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1

volumes:
  puzzler_postgres_data:
    name: puzzler_postgres_data
    labels:
      project: "puzzler"
  puzzler_pgadmin_data:
    name: puzzler_pgadmin_data
    labels:
      project: "puzzler"