name: Deploy to Vercel with Version Info

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Get version info
      id: version
      run: |
        echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        echo "COMMIT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        echo "BUILD_DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_OUTPUT
    
    - name: Run tests
      run: |
        # Run tests but exclude API tests that require backend
        npm test -- --run --exclude="**/api/**" || true
      continue-on-error: true
    
    - name: Build with version info
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        VITE_COMMIT_SHA: ${{ steps.version.outputs.COMMIT_SHA }}
        VITE_BUILD_DATE: ${{ steps.version.outputs.BUILD_DATE }}
        VITE_DEPLOYMENT_URL: https://puzzlator.vercel.app
    
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
    
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
    
    - name: Build Project Artifacts
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
    
    - name: Deploy to Vercel
      id: deploy
      run: |
        DEPLOYMENT_URL=$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})
        echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
    
    - name: Comment deployment info on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const version = '${{ steps.version.outputs.PACKAGE_VERSION }}';
          const commit = '${{ steps.version.outputs.COMMIT_SHA }}';
          const url = '${{ steps.deploy.outputs.DEPLOYMENT_URL }}';
          const date = '${{ steps.version.outputs.BUILD_DATE }}';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🚀 **Deployment successful!**
            
            - **Version**: ${version}
            - **Commit**: ${commit}
            - **Build Date**: ${date}
            - **URL**: ${url}
            
            To view version info in the app, add \`?version\` to the URL.`
          })
      
  setup-database:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
    
    - name: Run Database Migrations
      run: |
        # Only run if we have Supabase configured
        if [ -n "${{ secrets.SUPABASE_DB_URL }}" ]; then
          echo "Running database migrations..."
          supabase db push --db-url="${{ secrets.SUPABASE_DB_URL }}"
        else
          echo "Supabase not configured, skipping migrations"
        fi
      continue-on-error: true